use std::fmt;

use crate::{Location, TokenKind};

/// A token generated by the lexer.
#[derive(Clone)]
pub struct Token {
    pub(crate) kind: TokenKind,
    pub(crate) data: String,
    pub(crate) loc: Location,
}

impl Token {
    pub(crate) fn new(kind: TokenKind, data: String) -> Self {
        Self {
            kind,
            data,
            loc: Location::new(0),
        }
    }

    /// Get a reference to the token's kind.
    pub fn kind(&self) -> TokenKind {
        self.kind
    }

    /// Get a reference to the token's data.
    pub fn data(&self) -> &str {
        self.data.as_str()
    }

    /// Get a reference to the token's loc.
    pub fn loc(&self) -> Location {
        self.loc
    }
}

impl fmt::Debug for Token {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let start = self.loc.index;
        let end = self.loc.index + self.data.len();

        match &self.kind {
            TokenKind::Root => {
                write!(f, "ROOT@{}:{}", start, end)
            }
            TokenKind::Bang => {
                write!(f, "BANG@{}:{}", start, end)
            }
            TokenKind::Dollar => {
                write!(f, "DOLLAR@{}:{}", start, end)
            }
            TokenKind::Spread => {
                write!(f, "SPREAD@{}:{}", start, end)
            }
            TokenKind::Colon => {
                write!(f, "COLON@{}:{}", start, end)
            }
            TokenKind::Comma => {
                write!(f, "COMMA@{}:{}", start, end)
            }
            TokenKind::Eq => {
                write!(f, "EQ@{}:{}", start, end)
            }
            TokenKind::At => {
                write!(f, "AT@{}:{}", start, end)
            }
            TokenKind::LParen => {
                write!(f, "L_PAREN@{}:{}", start, end)
            }
            TokenKind::RParen => {
                write!(f, "R_PAREN@{}:{}", start, end)
            }
            TokenKind::LBracket => {
                write!(f, "L_BRACKET@{}:{}", start, end)
            }
            TokenKind::RBracket => {
                write!(f, "R_BRACKET@{}:{}", start, end)
            }
            TokenKind::LCurly => {
                write!(f, "L_CURLY@{}:{}", start, end)
            }
            TokenKind::RCurly => {
                write!(f, "R_CURLY@{}:{}", start, end)
            }
            TokenKind::Pipe => {
                write!(f, "PIPE@{}:{}", start, end)
            }
            TokenKind::Eof => {
                write!(f, "EOF@{}:{}", start, end)
            }

            // composite nodes
            TokenKind::Name => {
                write!(f, "NODE@{}:{} {:?}", start, end, self.data)
            }
            TokenKind::StringValue => {
                write!(f, "STRING_VALUE@{}:{} {:?}", start, end, self.data)
            }
            TokenKind::Int => {
                write!(f, "INT@{}:{} {:?}", start, end, self.data)
            }
            TokenKind::Float => {
                write!(f, "FLOAT@{}:{} {:?}", start, end, self.data)
            }
        }
    }
}
