[package]
name = "xtask"
version = "0.1.0"
publish = false
edition = "2021"

[dependencies]
ungrammar = "1.14.5"
proc-macro2 = "1.0.8"
quote = "1.0.2"
xshell = "0.2"
anyhow = "1"
clap = { version = "4.1.8", features = ["derive"] }
